[tool.poetry]
name = "unclogger"
version = "0.1.0"
description = "Custom wrapper for enhanced structured logging."
authors = ["Berislav Lopac <berislav@lopac.net>"]

[tool.poetry.dependencies]
python = "^3.8"
structlog = "^22.1.0"

[tool.poetry.group.dev.dependencies]
pytest = ">=7.1.2"
pytest-cov = ">=3.0.0"
flake8 = ">=5.0.2"
pytest-mock = ">=3.8.2"
mypy = ">=0.971"
pydocstyle = ">=6.1.1"
pytest-mypy = ">=0.9.1"
mkapi = ">=1.0.14"
black = ">=22.6.0"
pytest-spec = ">=3.2.0"
tox = ">=3.25.1"
tox-poetry = ">=0.4.1"
isort = ">=5.10.1"
toml = "^0.10.2"
mutmut = "^2.4.1"

[tool.poetry.group.docs.dependencies]
mkdocs = ">=1.3.0"
mkdocs-material = "^8.5.6"
pymdown-extensions = "^9.9"

[tool.pytest.ini_options]
minversion = "6.0"

[tool.coverage.run]
source = [ "unclogger/", ]
omit = [ "*/tests/*", "src/tests/*", ]

[tool.coverage.report]
skip_covered = false
show_missing = true
fail_under = 90
exclude_lines = [ "pragma: no cover", "@abstract",]

[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310']
verbose = false
skip-string-normalization = false

[tool.isort]
profile = "black"
line_length = 100
filter_files = true
force_alphabetical_sort_within_sections = true

[tool.mypy]
mypy_path = "unclogger/"
ignore_missing_imports = true

[tool.pydocstyle]
add-ignore = "D105, D107, D212, D401"
convention = "google"
match-dir = "(?!tests).*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
